
#Mod settings
[plainappletree]
	#1-in-N chance of a bonus second apple when harvesting a fruited leaf block. Lower = more likely (e.g. 4 means a 25% chance). Set to 0 to always drop exactly 1 apple.
	#Range: 0 ~ 1000
	bonusAppleChance = 4
	#Same as fruitRegrowChance, but when the leaf block is waterlogged. Lower = faster.
	#Range: 1 ~ 1000
	appleRegrowChanceWaterlogged = 5
	#1-in-N chance per random tick for a bare apple_leaves block to regrow its fruit. Lower = faster. Governed by the randomTickSpeed gamerule.
	#Range: 1 ~ 1000
	appleRegrowChance = 20

